# https://github.com/JohnnyMorganz/StyLua
column_width = 80
line_endings = "Unix"
indent_type  = "Spaces"
indent_width = 4
quote_style  = "AutoPreferDouble"

call_parentheses = ["NoSingleString", "NoSingleTable"]
collapse_simple_statement = "FunctionOnly"

[sort_requires]
enabled = false
